version: '3.1'

services:
  detectify: 
    image: detectify:v1.0
    build: .
    ports:
      - 8000:8000
    environment:
      - APP_ADDRESS=0.0.0.0
      - APP_PORT=8000
      - DEBUG=True
    command: ["python", "detectify/api.py"]