apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilenet-deployment
  labels:
    app: mobilenet-deployment
spec:
  template:
    metadata:
      name: mobilenet-api
      labels:
        app: mobilenet
    spec:
      containers:
        - name: mobilenet-container
          image: tareqz/mobilenet:latest
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
  replicas: 2
  selector:
    matchLabels:
      app: mobilenet
    